### ISSUE TITLE
two comments

### ISSUE THREAD

**Issue by questor** [floooh/sokol-tools#1]
While testing the shader tool I found two issues:
- enabling include support does not work for me, I can enable it as an extension, but it's not working and I dunno why (searchpath missing?). I think this needs to be handled in two steps, first making includes working and the second is adding support to add include directories via the commandline
- currently there is a headfile generated, but for some usecases it would be great to have separate files generated (for example for live-reloading of shaders). maybe splitting the output to vertex/fragment and headerfile as a commandline option would be a solution?

**Comment by floooh** [comment]
Hi, I was planning to add include-support as a tag (@include_file) instead of the GLSL extension, because:

- include files should also contain tags, not just plain GLSL code
- I need to keep track of line numbers also in included files, because I need to map GLSL line numbers back to their original file/line pairs when translating error messages.

Include file support will not be in the first version though.

More control over the generated output file will also come at a later time, especially for loading shader source and reflection data at runtime instead of the current "static code generation".

This might be interesting for this case though: https://github.com/septag/glslcc

It's less hardwired to sokol_gfx.h but (AFAIK) usable with sokol_gfx.h

**Comment by questor** [comment]
thanks, will close the ticket :)
