### ISSUE TITLE
Zig and Sokol-Shdc

### ISSUE THREAD

**Issue by Interrupt** [floooh/sokol-tools#117]
Two notes about using the Zig target for `sokol-shdc` when making a Material system:

* Zig target does not seem to honor the `--reflection` argument - I'm not seeing any extra data get baked into the .zig output file.
* Since Zig is already namespaced under the import name, it would be nice to have the function that builds the file to be named something more generic like `pub fn getShaderDesc(backend: sg.Backend) sg.ShaderDesc { ...` to work better with Zig reflection when making a Material system.

**Comment by floooh** [comment]
Thanks! Yeah, not supporting `--reflection` is more or less an oversight.

The second one is a bit more tricky though, since there may be multiple shaders in the same .glsl file, and each generates its own `getShaderDesc()` function.

The solution is probably to add a nested per-shader namespace:

```zig
// per-shader namespace struct
pub const Bla = struct {
    pub fn shaderDesc(backend: sg.Backend) sg.ShaderDesc { ... }
}
```

...that way it should be possible to walk the imported toplevel struct and find all shaders and getShaderDesc() functions.

I wonder if the whole shader-reflection stuff could also be simplified when taking Zig's comptime stuff into account... e.g. instead of having runtime functions to query the reflection information just add constants to the per-shader-namespace struct which can then be discovered by inspecting the struct via Zig's comptime type reflection.

So far the language binding backends in sokol-shdc are more or less copies of the C backend. But it might be worth supporting language-specifics a bit more.

**Comment by Interrupt** [comment]
Having a per-shader namespace like that would help out a lot - that would make it way more usable from a Zig point of view.

As for the reflection, I think you're right in that adding constants to that namespace also makes a lot of sense.

**Comment by floooh** [comment]
Closing this now as completed via https://github.com/floooh/sokol-tools/pull/147 (thanks!).

If we want to change the way reflection works in the Zig codegen we should do this via new issues.
