### ISSUE TITLE
Input vertex attribute slot constants get duplicated when a single vertex shader is used in multiple programs

### ISSUE THREAD

**Issue by jakubtomsu** [floooh/sokol-tools#150]
I need to support opaque, alpha clip and alpha dither meshes in my 3d rendering engine. This means I need 3 very slightly different variations of one pipeline. But when I try to reuse the vertex shader between all the `@program` definitions, the code generator generates the `ATTR_mesh_opaque/clip/dither_vs_pos/uv/etc` constants multiple times, once for each program.
Of course this then triggers the constant redefinition compiler error. Maybe not a problem in C with macro re-declarations, but Odin doesn't allow this.

The workaround is to put the vertex shader code in a `@block` and then do `@vs model_opaque_vs @include_block model_vs_block...` but it's not as nice, plus it's not very intuitive solution in case a beginner ran into this.

**Comment by floooh** [comment]
Hmm I could have sworn something similar was fixed a little while ago in sokol-shdc, let me check...

**Comment by floooh** [comment]
Here: https://github.com/floooh/sokol-tools/issues/133

There was a regression which indeed generated duplicate vertex attribute constants, but this should have been fixed by the related PR https://github.com/floooh/sokol-tools/pull/134 (which also has changes in the Odin code generator).

Are on an older sokol-shdc version perhaps? (the fix is from about 2.5 months ago).

**Comment by jakubtomsu** [comment]
oooh yeah that's it, I completely forgot I use an older version. I generally like to stick with one version I know works well and then do a big update every few months, go through changelogs and make sure everything works.

So I'll make sure to update soon, thank you for letting me know!
