### ISSUE TITLE
sokol-shdc: Uniform block field has wrong type on Metal

### ISSUE THREAD

**Issue by jpochyla** [floooh/sokol-tools#32]
When compiling code:
```
...
uniform fs_trace_params {
    float shape_materials[512]; // <== float here
    vec4 shape_vertices[512];
    float frame;
    float shape_count;
};
...
```

following struct is generated:
```
struct fs_trace_params
{
    float4 shape_materials[512]; // <== float4 here
    float4 shape_vertices[512];
    float frame;
    float shape_count;
};
```

Thank you very much for the tool btw!

**Comment by floooh** [comment]
I think this is an unfortunate side effect from the behaviour described here:

https://github.com/KhronosGroup/SPIRV-Cross/issues/1313#issuecomment-610303727

Don't know if that can be fixed in any meaningful way. There are also a couple different related problems with arrays of types that are smaller than vec4.

**Comment by floooh** [comment]
Closing this ticket, since the latest changes in sokol-shdc have tighter uniform block interior validation (e.g. arrays are only allowed for the types int4, float4 and mat4, everything else produces an error). Once the GLES2/WebGL1 backends are removed from sokol_gfx.h, those restrictions can probably be relaxed again.
