### ISSUE TITLE
shaders with arrays of floats generate incorrect Metal uniforms

### ISSUE THREAD

**Issue by prime31** [floooh/sokol-tools#44]
An example input uniform of `float radius[20];` will end up with a Metal uniform of `float4 radius[20];`. It seems that `vec2 radius[20];` and `vec3 radius[20];` also generate `float4 radius[20];` for Metal.

**Comment by floooh** [comment]
Yes, there are various known issues around uniform arrays (if you look through the other open sokol-shdc bugs quite a few are related to arrays. SPIRVCross generally seems to expand arrays to float4 (e.g. the GLSL generator also has this behaviour), however the SPIRV that's going into SPIRVCross still has the "correct" array sizes, and this is where the reflection information for the generated C struct is taken:

https://github.com/floooh/sokol-tools/blob/ad016969eedfa3152f44ff7c4d4d460a4a5011d8/src/shdc/spirvcross.cc#L99-L119

...but the code that's coming out of SPIRVCross generally seems to expand arrays to float4, which results in a mismatch between the C struct and the shader code.

I think this behaviour has changed in SPIRVCross at some point and the breakage was introduced by one of the SPIRVCross updates in sokol-shdc.

For now the workaround is to use float4 arrays. I think this is also a good idea after the memory layout bug is fixed, because SPIRVCross will expand the arrays anyway, resulting in lots of waste.

**Comment by floooh** [comment]
I'm closing the ticket because with the recent uniform block validation changes this behaviour has been cleaned up.

Uniform arrays are now only allowed for the following types: float4, int4 and mat4. This restriction is currently needed because the array element alignment is different between the std140 packing rule (where it is always 16 bytes), and the element stride expected by glUniform calls (where it is 4, 8, 12 or 16 bytes).

Any 'non-conforming' uniform block should now throw an error already in sokol-shdc. Once GLES2/WebGL1 support is removed from sokol_gfx.h, those restrictions won't apply anymore.
