### ISSUE TITLE
Fixing binding slot for multiple samplers is not working

### ISSUE THREAD

**Issue by edubart** [floooh/sokol-tools#51]
The README states this:

```
Just like with uniform blocks, texture sampler bind slots can be defined explicitely in the GLSL shader:

layout(binding=0) uniform sampler2D tex;
```

but when I fix the binding slot in the following example:
```c
@vs effect_vs
in vec4 coord;
out vec2 fragUV;
void main() {
    gl_Position = vec4(coord.xy, 0.0, 1.0);
    fragUV = coord.zw;
}
@end

@fs effect_fs
layout(binding=0) uniform sampler2D iChannel0;
layout(binding=1) uniform sampler2D iChannel1;
in vec2 fragUV;
out vec4 fragColor;
float noise(vec2 p) {
    return texture(iChannel1, p).r;
}
void main() {
    vec3 tex_col = texture(iChannel0, fragUV).rgb;
    float f = noise(fragUV);
    vec3 col = mix(tex_col, vec3(f), 0.5);
    fragColor = vec4(col,1.0);
}
@end

@program effect effect_vs effect_fs

```
I get this generated:
```c
#define SLOT_iChannel1 (0)
#define SLOT_iChannel0 (1)
```
But what I expected was:
```c
#define SLOT_iChannel1 (1)
#define SLOT_iChannel0 (0)
```

This means that I still need to use `SLOT_iChannel0` macro instead using just a constant number. 

I've noticed the binding behavior has changed recently, this means that using `layout(binding=0)` is not effectively anymore or this is a bug? If a bug, does binding a sampler should work for all targets (GLSL, HLSL, etc)?

PS: I've used latest sokol tool for Linux from the binary repository.

**Comment by floooh** [comment]
IFIR I was running into problems with manual bindslot-definitions at one point, but I don't remember the details and would need to dig into this again (it was most likely around the time I worked on sokol_gfx.h's WIP WebGPU backned).

There's a piece of code here which tells glslangValidator (which compiles GLSL into SPIRV) to automatically map the bindings (that "where" is a typo, should be "we're"), and overwrite any manually declared bindings for resources:

https://github.com/floooh/sokol-tools/blob/eacb50ff3deb52bf7bfbb0c7ed0860a687df20e7/src/shdc/spirv.cc#L170-L176

...and then for the SPIRVCross pass, this code explicitely sets the bind slots following a couple of rules:

https://github.com/floooh/sokol-tools/blob/eacb50ff3deb52bf7bfbb0c7ed0860a687df20e7/src/shdc/spirvcross.cc#L52-L87

IFIR, those changes were necessary for the GLSL => SPIRV => GLSL => SPIRV (not a typo) transformation that happens for WebGPU. Looking at the comment there I guess that the documentation is outdated.

I haven't considered sharing common bind slots between different shaders at all though, hmm.... so it's not really a bug, but also not really great, and I don't have a "quick fix" at hand.

**Comment by PeterHiber** [comment]
Had just finished writing up a new issue for this and then I saw that there already was one 😅 Might as well post it here anyway, it contains an additional repro:

According to the `sokol_shdc` documentation you can [explicitly define bind points for images](https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#binding-images) using the normal `layout(binding = x)` glsl syntax. However, this does unfortunately not seem to work properly. Instead, textures are always assigned bindings based on first order of appearance in the shader.

```glsl
@block VSBlock
in vec3 inPos;
in vec2 inTexcoord;
out vec2 texcoord;
void main()
{
	gl_Position = vec4(inPos.xyz, 1.0);
	texcoord = inTexcoord;
}
@end

@block PSBlock
in vec2 texcoord;
out vec4 fragColor;

layout(binding = 0) uniform sampler2D tex;
layout(binding = 1) uniform sampler2D tex2;

void main()
{
	vec3 res = vec3(0.0);
#if defined(REVERSE)
	res += texture(tex, texcoord).rgb;
	res += texture(tex2, texcoord).rgb;
#else
	res += texture(tex2, texcoord).rgb;
	res += texture(tex, texcoord).rgb;
#endif
	fragColor = vec4(res, 1.0);
}
@end

@vs TestVS
@glsl_options fixup_clipspace
@include_block VSBlock
@end

@fs TestPS
@include_block PSBlock
@end

@fs TestReversePS
#define REVERSE
@include_block PSBlock
@end

@program NormalShader TestVS TestPS
@program ReverseShader TestVS TestReversePS

```

In above example `tex` should always be assigned `binding = 0` and `tex2` always `binding = 1`. But what happens is that for the `ReverseShader` program it becomes the opposite because `tex2` happened to be used before `tex1`.

This is quite a major issues because not only are the bindings not what you expected, it's also a compile error in sokol_shdc which can be quite annoying to work around for "uber shaders". In fact, this is part of a bigger series of issues we have with building "uber shaders" with sokol_gfx and sokol_shdc. The second big issue is that sokol_gfx does not allow non-continuous binding ranges for textures, which is very annoying for "uber shaders". But that should probably be another issue. :)

**Comment by nmr8acme** [comment]
I think until which time as support for binding/layout is restored, it would be best to remove mention of it from the documentation, e.g. https://github.com/nmr8acme/sokol-tools/commit/fdf27f8d5cb889df23f10245e485d97d327138ae

IIUC I think support could be restored, with the caveat that custom binding slots for UBOs could not be re-used between FS and VS due to WebGPU constraints. (AFAICT even when enabling autoMapLocations and autoMapBindings glslang still respects explicit binding/layout directives.)
