### ISSUE TITLE
sokol-shdc crashes with int uniform

### ISSUE THREAD

**Issue by timeinpixels** [floooh/sokol-tools#58]
Hi,

I have an issue generating shaders which contain uniform blocks with int values - sokol-shdc crashes.
Example:

**(1) This works**

```glsl
@fs fs

uniform vs_params {
    vec2 offset0;
};

uniform sampler2D tex;

in vec4 color;
out vec4 frag_color;

void main() {
    frag_color = texture(tex,
        vec2(color.y + offset0.x, color.x * distance(color.xyz, vec3(0.0, 0.0, 0.0))));
}

@end
```

**(2) This crashes:**

```glsl
@fs fs

uniform vs_params {
    vec2 offset0;
    int x;
};

uniform sampler2D tex;

in vec4 color;
out vec4 frag_color;

void main() {
    frag_color = texture(tex,
        vec2(color.y + offset0.x + float(x), color.x * distance(color.xyz, vec3(0.0, 0.0, 0.0))));
}

@end
```

Is there any way to make it work?
Thanks in advance.

**Comment by floooh** [comment]
Hmm, when I try this on macOS (with GLSL output) it doesn't crash, but abort with an error message:

```
There was a compiler error: All basic types in a flattened block must be the same.
[1]    51609 abort      ./sokol-shdc -i bla.glsl -o bla.h -l glsl330
```

It works for HLSL and MSL outputs.

The reason why it doesn't work on GLSL is that SPIRVCross flattens uniform blocks into a vec4 array (so that the upload into GL can be done with a single glUniform4fv() call). This is only supported if uniform blocks don't mix types. 

It works if you split the float and int types into separate uniform blocks:

```
@fs fs

uniform vs_params_flt {
    vec2 offset0;
};

uniform vs_params_int {
    int y;
    int x;
};

uniform sampler2D tex;

in vec4 color;
out vec4 frag_color;

void main() {
    frag_color = texture(tex,
        vec2(color.y + offset0.x + float(x), color.x * distance(color.xyz, vec3(0.0, 0.0, 0.0))));
}

@end
```

But don't get your hopes up, sokol_gfx.h currently only supports float uniform types:

https://github.com/floooh/sokol/blob/dfe57a9d8d765dc5e689d238127558dafa72b7a3/sokol_gfx.h#L1205-L1214

Adding additional types will require both the SPIRVCross and sokol_gfx.h GL backend to fall back treating uniform blocks as unique uniforms (not a big deal, and it's on the todo list, but it's currently not a high priority).

**Comment by floooh** [comment]
...ok one remaining problem in sokol-shdc is that the generated C struct for a uniform block with an 'unsupported' type looks like this:

```
SOKOL_SHDC_ALIGN(16) typedef struct bla_params2_t {
    INVALID_UNIFORM_TYPE;
} bla_params2_t;
```

(I was hoping that the sokol-gfx GLSL 3.3 backend can be tricked into accepting non-float uniform data).

**Comment by floooh** [comment]
PPS: this looks like a good next thing to implement after my current emulator coding session...

**Comment by timeinpixels** [comment]
Thanks for the quick reply! It all makes sense now. I should be able to workaround it for now.
